In [ ]:
# load the dataset but only keep the top n words, zero the rest
import tensorflow as tf

num_words_to_keep = 5000
(X_train, y_train), (X_test, y_test) = tf.keras.datasets.imdb.load_data(num_words=num_words_to_keep)
# pad dataset to a maximum review length in words
max_words = 500
X_train = tf.keras.utils.pad_sequences(X_train, maxlen=max_words)
X_test = tf.keras.utils.pad_sequences(X_test, maxlen=max_words)

# Attention layer of TensorFlow

In [ ]:
text_input = tf.keras.Input(shape=(None,))

text_embeddings = tf.keras.layers.Embedding(num_words_to_keep, 32, input_length=max_words)(text_input)

x = tf.keras.layers.Conv1D(
    filters=100,
    kernel_size=4,
    padding='same')(text_embeddings)

sequence_encoding = tf.keras.layers.LSTM(100, return_sequences=True)(text_embeddings)

attention_sequence = tf.keras.layers.Attention(use_scale=True, dropout=0.6)(
    [sequence_encoding, sequence_encoding])

query_encoding = tf.keras.layers.GlobalAveragePooling1D()(
    sequence_encoding)
query_value_attention = tf.keras.layers.GlobalAveragePooling1D()(
    attention_sequence)

concat_layer = tf.keras.layers.Concatenate()(
    [query_encoding, query_value_attention])

outputs = tf.keras.layers.Dense(1)(concat_layer)
model = tf.keras.Model(inputs=text_input, outputs=outputs)
model.compile(loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
              optimizer=tf.keras.optimizers.Adam(1e-4),
              metrics=['accuracy'])
model.summary()

Model: "model_17"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_28 (InputLayer)          [(None, None)]       0           []                               
                                                                                                  
 embedding_27 (Embedding)       (None, None, 32)     160000      ['input_28[0][0]']               
                                                                                                  
 lstm_33 (LSTM)                 (None, None, 100)    53200       ['embedding_27[0][0]']           
                                                                                                  
 attention_25 (Attention)       (None, None, 100)    1           ['lstm_33[0][0]',                
                                                                  'lstm_33[0][0]']         

In [ ]:
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=20, batch_size=128, verbose=2)

Epoch 1/20
196/196 - 49s - loss: 0.6913 - accuracy: 0.5007 - val_loss: 0.6858 - val_accuracy: 0.5000 - 49s/epoch - 252ms/step
Epoch 2/20
196/196 - 28s - loss: 0.6366 - accuracy: 0.5692 - val_loss: 0.6041 - val_accuracy: 0.5713 - 28s/epoch - 143ms/step
Epoch 3/20
196/196 - 23s - loss: 0.5518 - accuracy: 0.6592 - val_loss: 0.5365 - val_accuracy: 0.6678 - 23s/epoch - 119ms/step
Epoch 4/20
196/196 - 20s - loss: 0.5145 - accuracy: 0.7435 - val_loss: 0.6130 - val_accuracy: 0.6478 - 20s/epoch - 102ms/step
Epoch 5/20
196/196 - 18s - loss: 0.5256 - accuracy: 0.7250 - val_loss: 0.5001 - val_accuracy: 0.6822 - 18s/epoch - 94ms/step
Epoch 6/20
196/196 - 19s - loss: 0.4434 - accuracy: 0.7868 - val_loss: 0.4688 - val_accuracy: 0.7923 - 19s/epoch - 98ms/step
Epoch 7/20
196/196 - 18s - loss: 0.4548 - accuracy: 0.7660 - val_loss: 0.4761 - val_accuracy: 0.7184 - 18s/epoch - 89ms/step
Epoch 8/20
196/196 - 17s - loss: 0.4096 - accuracy: 0.7987 - val_loss: 0.4566 - val_accuracy: 0.7777 - 17s/epoch - 86ms/s

In [ ]:
model.evaluate(X_test, y_test, verbose=2)

782/782 - 3s - loss: 0.3174 - accuracy: 0.8756 - 3s/epoch - 4ms/step
Accuracy: 87.56%


# Custom Attention Layer

In [ ]:
class Attention(tf.keras.layers.Layer):
    def __init__(self, return_sequences=True):
        self.return_sequences = return_sequences
        super(Attention,self).__init__()

    def build(self, input_shape):
        self.W=self.add_weight(shape=(input_shape[-1],1), initializer="normal")
        self.b=self.add_weight(shape=(input_shape[1],1), initializer="zeros")
        super(Attention,self).build(input_shape)

    def call(self, x):
        dot_prod = tf.keras.activations.tanh(tf.matmul(x,self.W)+self.b)
        attention = tf.keras.activations.softmax(dot_prod, axis=1)
        out_sequences = x*attention

        if self.return_sequences:
            return out_sequences

        return tf.math.reduce_sum(out_sequences, axis=1)

In [ ]:
text_input = tf.keras.Input(shape=(max_words,))

x = tf.keras.layers.Embedding(num_words_to_keep, 32, input_length=max_words)(text_input)
x = tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(32, return_sequences=True))(x)
x = Attention(return_sequences=True)(x)
x = tf.keras.layers.LSTM(32)(x)
outputs = tf.keras.layers.Dense(1)(x)
model = tf.keras.Model(inputs=text_input, outputs=outputs)
model.compile(loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
              optimizer=tf.keras.optimizers.Adam(1e-4),
              metrics=['accuracy'])
model.summary()

Model: "model_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_3 (InputLayer)        [(None, 500)]             0         
                                                                 
 embedding_2 (Embedding)     (None, 500, 32)           160000    
                                                                 
 bidirectional_2 (Bidirectio  (None, 500, 64)          16640     
 nal)                                                            
                                                                 
 attention_2 (Attention)     (None, 500, 64)           564       
                                                                 
 lstm_5 (LSTM)               (None, 32)                12416     
                                                                 
 dense_2 (Dense)             (None, 1)                 33        
                                                           

In [ ]:
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=20, verbose=2)

Epoch 1/20
782/782 - 129s - loss: 0.6925 - accuracy: 0.5003 - val_loss: 0.6932 - val_accuracy: 0.5000 - 129s/epoch - 166ms/step
Epoch 2/20
782/782 - 63s - loss: 0.6471 - accuracy: 0.5769 - val_loss: 0.5756 - val_accuracy: 0.7371 - 63s/epoch - 80ms/step
Epoch 3/20
782/782 - 58s - loss: 0.5536 - accuracy: 0.7565 - val_loss: 0.5596 - val_accuracy: 0.7521 - 58s/epoch - 74ms/step
Epoch 4/20
782/782 - 56s - loss: 0.5266 - accuracy: 0.7795 - val_loss: 0.5537 - val_accuracy: 0.7548 - 56s/epoch - 71ms/step
Epoch 5/20
782/782 - 53s - loss: 0.5107 - accuracy: 0.7904 - val_loss: 0.5271 - val_accuracy: 0.7795 - 53s/epoch - 67ms/step
Epoch 6/20
782/782 - 51s - loss: 0.4798 - accuracy: 0.8130 - val_loss: 0.5137 - val_accuracy: 0.7917 - 51s/epoch - 66ms/step
Epoch 7/20
782/782 - 52s - loss: 0.4436 - accuracy: 0.8356 - val_loss: 0.4743 - val_accuracy: 0.8148 - 52s/epoch - 67ms/step
Epoch 8/20
782/782 - 52s - loss: 0.4317 - accuracy: 0.8272 - val_loss: 0.4604 - val_accuracy: 0.8115 - 52s/epoch - 66ms/st

In [ ]:
# Final evaluation of the model
scores = model.evaluate(X_test, y_test, verbose=2)
print("Accuracy: %.2f%%" % (scores[1]*100))

782/782 - 13s - loss: 0.4699 - accuracy: 0.8632 - 13s/epoch - 17ms/step
Accuracy: 86.32%


# Transformer with BERT

In [ ]:
#!pip3 install tf-models-official
import tensorflow_models as tfm

/usr/local/lib/python3.10/dist-packages/tensorflow_addons/utils/tfa_eol_msg.py:23: UserWarning: 

TensorFlow Addons (TFA) has ended development and introduction of new features.
TFA has entered a minimal maintenance and release mode until a planned end of life in May 2024.
Please modify downstream libraries to take dependencies from other repositories in our TensorFlow community (e.g. Keras, Keras-CV, and Keras-NLP). 

For more information see: https://github.com/tensorflow/addons/issues/2807 

  warnings.warn(


# Transformer custom layer

In [ ]:
class TransformerLayer(tf.keras.layers.Layer):
    def __init__(self, embed_size, num_heads, ff_units, rate=0.1):
        super().__init__()
        self.attention = tf.keras.layers.MultiHeadAttention(num_heads=num_heads, key_dim=embed_size, dropout=rate)

        self.feedforward = tf.keras.Sequential()
        self.feedforward.add(tf.keras.layers.Dense(ff_units, activation="relu"))
        self.feedforward.add(tf.keras.layers.Dense(embed_size))

        self.layernormalization_1 = tf.keras.layers.LayerNormalization(epsilon=1e-6)
        self.layernormalization_2 = tf.keras.layers.LayerNormalization(epsilon=1e-6)

    def call(self, inputs):
        attn_output = self.attention(inputs, inputs)
        ln_out = self.layernormalization_1(inputs + attn_output)
        ff_output = self.feedforward(ln_out)
        return self.layernormalization_2(ln_out + ff_output)

class TokenAndPositionEmbedding(tf.keras.layers.Layer):
    def __init__(self, max_seq_len, vocab_size, embedding_dim):
        super().__init__()
        self.max_seq_len = max_seq_len
        self.token_embedding = tf.keras.layers.Embedding(input_dim=vocab_size, output_dim=embedding_dim)
        self.position_embedding = tf.keras.layers.Embedding(input_dim=max_seq_len, output_dim=embedding_dim)

    def call(self, x):
        position_tensor = tf.range(start=0, limit=self.max_seq_len, delta=1)
        position_tensor = self.position_embedding(position_tensor)
        x = self.token_embedding(x)
        return x + position_tensor

In [ ]:
embed_size = 32  # Embedding size for each token
num_heads = 2  # Number of attention heads
ff_units = 32  # Hidden layer size in feed forward network inside transformer

inputs = tf.keras.layers.Input(shape=(max_words,))
embedding_layer = TokenAndPositionEmbedding(max_words, num_words_to_keep, embed_size)
x = embedding_layer(inputs)
transformer_block = TransformerLayer(embed_size, num_heads, ff_units)
x = transformer_block(x)
x = tf.keras.layers.GlobalAveragePooling1D()(x)
x = tf.keras.layers.Dropout(0.1)(x)
x = tf.keras.layers.Dense(20, activation="relu")(x)
x = tf.keras.layers.Dropout(0.1)(x)
outputs = tf.keras.layers.Dense(1)(x)

model = tf.keras.Model(inputs=inputs, outputs=outputs)

In [ ]:
model.compile(loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
              optimizer=tf.keras.optimizers.Adam(1e-4),
              metrics=['accuracy'])
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=10, verbose=2)

Epoch 1/10
782/782 - 80s - loss: 0.6774 - accuracy: 0.5154 - val_loss: 0.6200 - val_accuracy: 0.5611 - 80s/epoch - 102ms/step
Epoch 2/10
782/782 - 36s - loss: 0.4564 - accuracy: 0.7597 - val_loss: 0.3417 - val_accuracy: 0.8642 - 36s/epoch - 46ms/step
Epoch 3/10
782/782 - 24s - loss: 0.2940 - accuracy: 0.8772 - val_loss: 0.2827 - val_accuracy: 0.8724 - 24s/epoch - 31ms/step
Epoch 4/10
782/782 - 21s - loss: 0.2550 - accuracy: 0.8955 - val_loss: 0.2734 - val_accuracy: 0.8878 - 21s/epoch - 27ms/step
Epoch 5/10
782/782 - 22s - loss: 0.2272 - accuracy: 0.9098 - val_loss: 0.2853 - val_accuracy: 0.8708 - 22s/epoch - 28ms/step
Epoch 6/10


KeyboardInterrupt: ignored

In [ ]:
embed_size = 32  # Embedding size for each token
num_heads = 2  # Number of attention heads
ff_units = 32  # Hidden layer size in feed forward network inside transformer

inputs = tf.keras.layers.Input(shape=(max_words,))
embedding = tf.keras.layers.Embedding(num_words_to_keep, embed_size)(inputs)
position = tfm.nlp.layers.PositionEmbedding(max_words)(embedding)
x = tf.keras.layers.add([embedding, position])
transformer_block = TransformerLayer(embed_size, num_heads, ff_units)
x = transformer_block(x)
x = tf.keras.layers.GlobalAveragePooling1D()(x)
x = tf.keras.layers.Dropout(0.1)(x)
x = tf.keras.layers.Dense(20, activation="relu")(x)
x = tf.keras.layers.Dropout(0.1)(x)
outputs = tf.keras.layers.Dense(1)(x)

model = tf.keras.Model(inputs=inputs, outputs=outputs)

In [ ]:
model.compile(loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
              optimizer=tf.keras.optimizers.Adam(1e-4),
              metrics=['accuracy'])
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=10, verbose=2)

Epoch 1/10
782/782 - 96s - loss: 0.6712 - accuracy: 0.5202 - val_loss: 0.5793 - val_accuracy: 0.6106 - 96s/epoch - 123ms/step
Epoch 2/10
782/782 - 39s - loss: 0.4137 - accuracy: 0.7956 - val_loss: 0.3189 - val_accuracy: 0.8702 - 39s/epoch - 49ms/step
Epoch 3/10
782/782 - 26s - loss: 0.2906 - accuracy: 0.8767 - val_loss: 0.2886 - val_accuracy: 0.8828 - 26s/epoch - 33ms/step
Epoch 4/10
782/782 - 20s - loss: 0.2547 - accuracy: 0.8957 - val_loss: 0.2890 - val_accuracy: 0.8870 - 20s/epoch - 25ms/step
Epoch 5/10
782/782 - 19s - loss: 0.2328 - accuracy: 0.9066 - val_loss: 0.3466 - val_accuracy: 0.8717 - 19s/epoch - 24ms/step
Epoch 6/10
782/782 - 21s - loss: 0.2179 - accuracy: 0.9146 - val_loss: 0.2755 - val_accuracy: 0.8864 - 21s/epoch - 26ms/step
Epoch 7/10
782/782 - 19s - loss: 0.2058 - accuracy: 0.9202 - val_loss: 0.2830 - val_accuracy: 0.8880 - 19s/epoch - 24ms/step
Epoch 8/10
782/782 - 20s - loss: 0.1968 - accuracy: 0.9248 - val_loss: 0.2873 - val_accuracy: 0.8867 - 20s/epoch - 25ms/step

# Transformer in-built layer

In [ ]:
inputs = tf.keras.layers.Input(shape=(max_words,))
embedding = tf.keras.layers.Embedding(num_words_to_keep, embed_size)(inputs)
position = tfm.nlp.layers.PositionEmbedding(max_words)(embedding)
x = tf.keras.layers.add([embedding, position])
x = tfm.nlp.layers.TransformerEncoderBlock(num_attention_heads=2, inner_dim=32, inner_activation="tanh")(x)
x = tf.keras.layers.GlobalAveragePooling1D()(x)
x = tf.keras.layers.Dropout(0.1)(x)
x = tf.keras.layers.Dense(20, activation="relu")(x)
x = tf.keras.layers.Dropout(0.1)(x)
outputs = tf.keras.layers.Dense(1)(x)
model = tf.keras.Model(inputs=inputs, outputs=outputs)
model.compile(loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
              optimizer=tf.keras.optimizers.Adam(1e-4),
              metrics=['accuracy'])
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=10, verbose=2)

Epoch 1/10
782/782 - 71s - loss: 0.6685 - accuracy: 0.5174 - val_loss: 0.6055 - val_accuracy: 0.5369 - 71s/epoch - 90ms/step
Epoch 2/10
782/782 - 25s - loss: 0.4436 - accuracy: 0.7706 - val_loss: 0.3286 - val_accuracy: 0.8611 - 25s/epoch - 32ms/step
Epoch 3/10
782/782 - 21s - loss: 0.2889 - accuracy: 0.8781 - val_loss: 0.2956 - val_accuracy: 0.8611 - 21s/epoch - 27ms/step
Epoch 4/10
782/782 - 17s - loss: 0.2541 - accuracy: 0.8953 - val_loss: 0.2838 - val_accuracy: 0.8712 - 17s/epoch - 22ms/step
Epoch 5/10
782/782 - 16s - loss: 0.2324 - accuracy: 0.9086 - val_loss: 0.2820 - val_accuracy: 0.8738 - 16s/epoch - 21ms/step
Epoch 6/10
782/782 - 17s - loss: 0.2172 - accuracy: 0.9134 - val_loss: 0.2808 - val_accuracy: 0.8832 - 17s/epoch - 22ms/step
Epoch 7/10
782/782 - 15s - loss: 0.2083 - accuracy: 0.9196 - val_loss: 0.2865 - val_accuracy: 0.8853 - 15s/epoch - 19ms/step
Epoch 8/10
782/782 - 16s - loss: 0.1968 - accuracy: 0.9259 - val_loss: 0.2939 - val_accuracy: 0.8728 - 16s/epoch - 20ms/step


# Text Data with pre-trained models

In [ ]:
#!pip install tensorflow-text

In [ ]:
preprocessor = hub.KerasLayer(bert_preprocessor)

In [ ]:
sample_text = ["I liked the movie."]
preprocessor(sample_text)

{'input_word_ids': <tf.Tensor: shape=(1, 128), dtype=int32, numpy=
 array([[ 101, 1045, 4669, 1996, 3185, 1012,  102,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0]], dtype=int32)>,
 'input_mask': <tf.Tensor: shape=(1, 128

In [ ]:
preprocessed_text = preprocessor(sample_text)
bert_model = hub.KerasLayer(bert_encoder)
bert_model(preprocessed_text)

{'pooled_output': <tf.Tensor: shape=(1, 128), dtype=float32, numpy=
 array([[ 0.14991051, -0.9954626 , -0.56467605,  0.5200906 ,  0.94665915,
         -0.84874946, -0.14203247, -0.01204591, -0.61475974,  0.24566683,
          0.99028355,  0.8796596 , -0.7936716 , -0.99752533, -0.98550725,
          0.9955794 , -0.02106644, -0.78096175, -0.9591398 ,  0.8717347 ,
          0.7848385 , -0.9927802 ,  0.04688101,  0.9444531 , -0.85566634,
          0.12791783,  0.8571924 ,  0.9116219 , -0.99501747,  0.91106576,
         -0.9990185 , -0.8794261 ,  0.98577243,  0.981804  , -0.03108696,
         -0.7667733 , -0.83929425, -0.2959756 ,  0.88645613, -0.02775686,
         -0.98970896, -0.848679  , -0.12696458, -0.9613154 ,  0.8818318 ,
         -0.99941665,  0.9997978 ,  0.92935616, -0.9775419 ,  0.9059332 ,
          0.9972643 , -0.9164398 , -0.9853943 , -0.99121577, -0.99890536,
          0.6356284 , -0.9954689 ,  0.8571265 , -0.99776185, -0.9986718 ,
         -0.7080523 , -0.84435934,  0.093862

In [ ]:
text_input = tf.keras.layers.Input(shape=(), dtype=tf.string)
preprocessor = hub.KerasLayer(bert_preprocessor)
preprocessed_text = preprocessor(text_input)
encoder = hub.KerasLayer(bert_encoder, trainable=True)
encoded_data = encoder(preprocessed_text)["pooled_output"]
x = tf.keras.layers.Dropout(rate=0.2)(encoded_data)
outputs = tf.keras.layers.Dense(1)(x)
model = tf.keras.Model(inputs=text_input, outputs=outputs)
model.compile(loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
              optimizer=tf.keras.optimizers.Adam(1e-4),
              metrics=['accuracy'])
model.fit(train_dataset, validation_data=test_dataset, epochs=4, verbose=2)

Epoch 1/4
391/391 - 266s - loss: 0.4957 - accuracy: 0.7422 - val_loss: 0.4099 - val_accuracy: 0.8217 - 266s/epoch - 679ms/step
Epoch 2/4
391/391 - 252s - loss: 0.3636 - accuracy: 0.8324 - val_loss: 0.3803 - val_accuracy: 0.8336 - 252s/epoch - 645ms/step
Epoch 3/4
391/391 - 206s - loss: 0.2817 - accuracy: 0.8804 - val_loss: 0.4661 - val_accuracy: 0.8240 - 206s/epoch - 527ms/step
Epoch 4/4
391/391 - 253s - loss: 0.2267 - accuracy: 0.9085 - val_loss: 0.4950 - val_accuracy: 0.8071 - 253s/epoch - 646ms/step


In [ ]:
model.evaluate(test_dataset)

391/391 [==============================] - 104s 266ms/step - loss: 0.4950 - accuracy: 0.8071


[0.4950130581855774, 0.8070799708366394]

In [ ]:
sentence = tf.constant(["I liked the movie. In fact, I liked it so much that I watched it three times: twice in two days, and once more a week after."])
print(model(sentence))

tf.Tensor([[3.754312]], shape=(1, 1), dtype=float32)


In [ ]:
sentence = tf.constant(["I disliked the movie."])
print(model(sentence))

tf.Tensor([[-3.8075325]], shape=(1, 1), dtype=float32)


# Hugging Face

In [ ]:
#!pip install transformers

In [ ]:
from transformers import GPT2Tokenizer, TFGPT2Model
tokenizer = GPT2Tokenizer.from_pretrained('gpt2')
model = TFGPT2Model.from_pretrained('gpt2')
text = "This is my first text."
encoded_input = tokenizer(text, return_tensors='tf')
output = model(encoded_input)

All PyTorch model weights were used when initializing TFGPT2Model.

All the weights of TFGPT2Model were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFGPT2Model for predictions without further training.


In [ ]:
output.keys()

odict_keys(['last_hidden_state', 'past_key_values'])

In [ ]:
from transformers import pipeline
text_generator = pipeline('text-generation', model='gpt2')
input_text = "I work as a"
res = text_generator(input_text, max_length=20, num_return_sequences=5)
res

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


[{'generated_text': "I worked as a urn manager for Microsoft's Windows 10 Mobile store. During the course of this"},
 {'generated_text': 'I worked as a _____" on the right track, the best I\'ve ever had a chance'},
 {'generated_text': "I worked as a urchin farmer in the hills of Nara'i. We were very"},
 {'generated_text': 'I worked as a ichthyologist for 27 years. You know, I spent many nights in'},
 {'generated_text': 'I worked as a ichor designer to produce these gorgeous, high quality products, including the original'}]

In [ ]:
text_generator = pipeline('text-generation', model='openai-gpt')
input_text = "I work as a"
res = text_generator(input_text, max_length=20, num_return_sequences=5)
res

Some weights of OpenAIGPTLMHeadModel were not initialized from the model checkpoint at openai-gpt and are newly initialized: ['position_ids']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


[{'generated_text': 'I work as a bookkeeping manager. " \n " that\'s right, " i interjected in an'},
 {'generated_text': 'I work as a detective. " \n " you will? " \n " yes. i can\'t'},
 {'generated_text': "I work as a secretary for the firm and i have to get to a meeting i know i'm"},
 {'generated_text': "I work as a receptionist. i wouldn't tell you unless you asked. not that you 'd ask"},
 {'generated_text': 'I work as a security guard at the hotel. \n " aren\'t you going to ask her?'}]

In [ ]:
text_classifier = pipeline("text-classification")
input_texts = ["I liked the movie. In fact, I liked it so much that I watched it three times: twice in two days, and once more a week after.",
               "The movie was a waste of time and money. For the 150 minutes, I enjoyed only the popcorn",
               "The place is far from my home. I do not like to go there."
               ]
res = text_classifier(input_texts)
res

No model was supplied, defaulted to distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.


[{'label': 'POSITIVE', 'score': 0.9996412992477417},
 {'label': 'NEGATIVE', 'score': 0.9960646033287048},
 {'label': 'NEGATIVE', 'score': 0.9571212530136108}]

# OpenAI

In [ ]:
#!pip install openai

In [ ]:
import openai
openai.api_key = "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"

prompt_text="""Make a summary of the below paragraph:

In common usage, climate change describes global warming—the ongoing increase in global average
temperature—and its effects on Earth's climate system. Climate change in a broader sense also includes
previous long-term changes to Earth's climate. The current rise in global average temperature is more rapid
than previous changes, and is primarily caused by humans burning fossil fuels. Fossil fuel use, deforestation,
and some agricultural and industrial practices increase greenhouse gases, notably carbon dioxide and methane.
Greenhouse gases absorb some of the heat that the Earth radiates after it warms from sunlight. Larger amounts
of these gases trap more heat in Earth's lower atmosphere, causing global warming."""

response = openai.Completion.create(
  model="text-davinci-003",
  prompt=prompt_text,
  temperature=0.8,
  max_tokens=500
)

response["choices"][0]["text"]

"\n\nClimate change is the global increase in average temperature, caused by humans burning fossil fuels, deforestation, and industrial practices. This increased temperature is trapping more heat in Earth's lower atmosphere, leading to a rise in global average temperature, faster than ever before, with effects on Earth's climate system."